############################
# STEP 1 build executable binary
############################
FROM golang:1.24-alpine AS builder

# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/deelfietsdashboard-importer
COPY . .

# Fetch dependencies.
# Using go get.
RUN go get -d -v
# Build the binary.
WORKDIR $GOPATH/src/deelfietsdashboard-importer/cmd/service_area_importer
RUN CGO_ENABLED=0 go build -o /go/bin/service-area-importer

############################
# STEP 2 build a small image
############################
FROM alpine
# Copy our static executable.
COPY --from=builder /go/bin/service-area-importer /go/bin/service-area-importer

CMD ["/go/bin/service-area-importer"]
